# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c794be39e1444ffeb9ef7a75f934496ed307356c585b05fe6913a39c02070bdbe539ea2542021f2c7be6aadbf03595f0b860bcffbe2236f9defea689f0f101ee

test:
  secret_key_base: e4944e26c9b7c0f6f3ba3c30c13b0ca93558b48cad5e8a1efcf753b7ec66f20a080244b1f2eb0254daa582a2b05ef184d70dfd43986131f84bcd7901b5f2c88b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
